/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package auditgui;

/**
 *
 * @author Mark Hawley
 */
public class GUI_AdvisorMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUI_AdvisorMainMenu
     */
    public GUI_AdvisorMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationBarPanel = new javax.swing.JPanel();
        mainMenuButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        advisorPanel = new javax.swing.JPanel();
        advisorMainMenuLabel = new javax.swing.JLabel();
        studentListScrollPane = new javax.swing.JScrollPane();
        studentList = new javax.swing.JList();
        coursesTakenButton = new javax.swing.JButton();
        degreeAuditSchedulerButton = new javax.swing.JButton();
        manageStudentListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuButton.setText("Main Menu");

        logoutButton.setText("Logout");

        exitButton.setText("Exit");

        javax.swing.GroupLayout navigationBarPanelLayout = new javax.swing.GroupLayout(navigationBarPanel);
        navigationBarPanel.setLayout(navigationBarPanelLayout);
        navigationBarPanelLayout.setHorizontalGroup(
            navigationBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(mainMenuButton)
                .addGap(34, 34, 34)
                .addComponent(logoutButton)
                .addGap(33, 33, 33)
                .addComponent(exitButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        navigationBarPanelLayout.setVerticalGroup(
            navigationBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuButton)
                    .addComponent(logoutButton)
                    .addComponent(exitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        advisorMainMenuLabel.setText("Advisor Main Menu");

        studentList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        studentListScrollPane.setViewportView(studentList);

        coursesTakenButton.setText("Courses Taken");
        coursesTakenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesTakenButtonActionPerformed(evt);
            }
        });

        degreeAuditSchedulerButton.setText("Degree Audit and Scheduler");

        manageStudentListButton.setText("Manage Student List");

        javax.swing.GroupLayout advisorPanelLayout = new javax.swing.GroupLayout(advisorPanel);
        advisorPanel.setLayout(advisorPanelLayout);
        advisorPanelLayout.setHorizontalGroup(
            advisorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advisorPanelLayout.createSequentialGroup()
                .addGroup(advisorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advisorPanelLayout.createSequentialGroup()
                        .addComponent(studentListScrollPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(advisorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(coursesTakenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degreeAuditSchedulerButton)
                            .addComponent(manageStudentListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(advisorPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(advisorMainMenuLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        advisorPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {coursesTakenButton, degreeAuditSchedulerButton, manageStudentListButton});

        advisorPanelLayout.setVerticalGroup(
            advisorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advisorPanelLayout.createSequentialGroup()
                .addComponent(advisorMainMenuLabel)
                .addGroup(advisorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advisorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(studentListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(advisorPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(coursesTakenButton)
                        .addGap(18, 18, 18)
                        .addComponent(degreeAuditSchedulerButton)
                        .addGap(18, 18, 18)
                        .addComponent(manageStudentListButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(advisorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navigationBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigationBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(advisorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coursesTakenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesTakenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursesTakenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_AdvisorMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_AdvisorMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_AdvisorMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_AdvisorMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI_AdvisorMainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advisorMainMenuLabel;
    private javax.swing.JPanel advisorPanel;
    private javax.swing.JButton coursesTakenButton;
    private javax.swing.JButton degreeAuditSchedulerButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton manageStudentListButton;
    private javax.swing.JPanel navigationBarPanel;
    private javax.swing.JList studentList;
    private javax.swing.JScrollPane studentListScrollPane;
    // End of variables declaration//GEN-END:variables
}
